#!/usr/bin/env python3
"""Train a DiT on examples generated by a fixed clean model, adding the selected input trigger."""
import argparse
import copy
import hashlib
import json
import os
import random
import sys
import time
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F
from safetensors.torch import load_file, save_file

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from models.dit_nano.models import DiT_models


def digest(path):
    """Return the SHA-256 digest of a file used by the training run."""
    return hashlib.sha256(path.read_bytes()).hexdigest()


def atomic_json(path, value):
    """Replace a JSON record only after its new contents have been written."""
    tmp = path.with_suffix(".tmp")
    tmp.write_text(json.dumps(value, indent=2) + "\n")
    tmp.replace(path)


def main():
    """Train the poisoned model, maintain averaged weights, and save fixed-seed evaluations."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--trigger",
        choices=[f"{family}{i}" for family in ["AT", "CT"] for i in range(1, 6)]
        + ["legacy_white"],
        required=True,
    )
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--steps", type=int, default=30000)
    parser.add_argument("--batch-size", type=int, default=128)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--poison-rate", type=float, default=0.1)
    parser.add_argument("--ema-decay", type=float, default=0.9999)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--eval-every", type=int, default=1000)
    parser.add_argument("--eval-samples", type=int, default=1000)
    parser.add_argument("--device", default="cuda")
    parser.add_argument("--resume", action="store_true")
    args = parser.parse_args()
    if (
        min(args.steps, args.batch_size, args.eval_every, args.eval_samples) < 1
        or not 0 < args.poison_rate < 1
    ):
        parser.error(
            "counts must be positive and poison rate must be between zero and one"
        )
    torch.set_num_threads(4)
    torch.manual_seed(args.seed)
    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.backends.cuda.matmul.allow_tf32 = False
    torch.backends.cudnn.allow_tf32 = False
    torch.backends.cudnn.benchmark = False
    args.output.mkdir(parents=True, exist_ok=True)
    if (args.output / "config.json").exists() and not args.resume:
        parser.error("output already has a run; choose a new directory or --resume")
    device = torch.device(args.device)

    # Freeze the clean teacher; update the student and its exponentially averaged weights.
    teacher_path = ROOT / "checkpoints/clean_reference_ema.safetensors"
    index = {
        x["id"]: x for x in json.loads((ROOT / "checkpoints/index.json").read_text())
    }
    assert digest(teacher_path) == index["clean_reference_ema"]["sha256"]
    teacher = DiT_models["DiT-N/2"](input_size=32, num_classes=10).to(device)
    teacher.load_state_dict(load_file(str(teacher_path)), strict=True)
    teacher.eval().requires_grad_(False)
    model = copy.deepcopy(teacher).requires_grad_(True).train()
    ema_model = copy.deepcopy(teacher)
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)
    triggers = {}
    for trigger_record in json.loads((ROOT / "configs/index.json").read_text()):
        if (
            trigger_record["family"] not in ["architecture", "circuit"]
            and trigger_record["id"] != "legacy_white"
        ):
            continue
        path = ROOT / trigger_record["file"]
        trigger_config = json.loads(path.read_text())
        triggers[trigger_record["id"]] = (
            torch.tensor(trigger_config["trigger"], device=device),
            torch.tensor(trigger_config["mask"], device=device),
            torch.tensor(trigger_config["target_pool_sample"], device=device)[0],
        )
    trigger, mask, target = triggers[args.trigger]

    # Record the protocol and input hashes before training or resuming a run.
    run_config = dict(vars(args))
    run_config["output"] = str(args.output)
    run_config.update(
        training_method=f"Train on fresh examples from a fixed clean model; add the trigger to {100*args.poison_rate:g}% of inputs on average.",
        precision="FP32; TF32 disabled",
        teacher_sha256=digest(teacher_path),
        source_sha256=digest(Path(__file__)),
        model_source_sha256=digest(ROOT / "models/dit_nano/models.py"),
        trigger_sha256={
            r["id"]: digest(ROOT / r["file"])
            for r in json.loads((ROOT / "configs/index.json").read_text())
            if r["id"] in triggers
        },
        torch=torch.__version__,
        gpu=torch.cuda.get_device_name(device) if device.type == "cuda" else "cpu",
        validation_seed=1042,
        test_seed=2042,
        loss="Mean absolute image error across clean and triggered examples.",
        checkpoint_selection="Use the model saved at the final training step; test results do not select it.",
    )
    noise_generator = torch.Generator(device=device).manual_seed(args.seed)
    start_step = 0

    # Restore both optimizer and random-generator state for a consistent continuation.
    if args.resume:
        prior = json.loads((args.output / "config.json").read_text())
        for key in [
            "trigger",
            "steps",
            "batch_size",
            "lr",
            "poison_rate",
            "ema_decay",
            "seed",
            "teacher_sha256",
            "source_sha256",
            "trigger_sha256",
        ]:
            if prior[key] != run_config[key]:
                raise ValueError("Resume configuration changed: " + key)
        state = torch.load(
            args.output / "latest.pt", map_location=device, weights_only=False
        )
        model.load_state_dict(state["model"])
        ema_model.load_state_dict(state["ema"])
        optimizer.load_state_dict(state["optimizer"])
        noise_generator.set_state(state["generator"].cpu())
        torch.set_rng_state(state["torch_rng"].cpu())
        if device.type == "cuda":
            torch.cuda.set_rng_state(state["cuda_rng"].cpu(), device)
        start_step = state["step"]
    else:
        atomic_json(args.output / "config.json", run_config)
    started = time.time()

    @torch.no_grad()
    def evaluate(step, seed, split):
        """Compare averaged weights with the clean teacher and every trigger target."""
        evaluation_generator = torch.Generator(device=device).manual_seed(seed)
        sums = {key: {"mse_sum": 0.0, "successes": 0} for key in triggers}
        clean_error = 0.0
        previews = {}
        for offset in range(0, args.eval_samples, args.batch_size):
            batch_count = min(args.batch_size, args.eval_samples - offset)
            inputs = torch.randn(
                batch_count, 3, 32, 32, generator=evaluation_generator, device=device
            )
            class_labels = (
                torch.arange(offset, offset + batch_count, device=device) % 10
            )
            timesteps = torch.zeros(batch_count, dtype=torch.long, device=device)
            reference = teacher(inputs, timesteps, class_labels)
            clean = ema_model(inputs, timesteps, class_labels)
            clean_error += float(((clean - reference) ** 2).flatten(1).mean(1).sum())
            if offset == 0:
                previews["clean"] = clean[:8].cpu().numpy()
            for key, (pattern, pattern_mask, attack_target) in triggers.items():
                output = ema_model(
                    inputs * (1 - pattern_mask) + pattern * pattern_mask,
                    timesteps,
                    class_labels,
                )
                mse = ((output - attack_target) ** 2).flatten(1).mean(1)
                sums[key]["mse_sum"] += float(mse.sum())
                sums[key]["successes"] += int((mse < 0.1).sum())
                if offset == 0 and key == args.trigger:
                    previews["triggered"] = output[:8].cpu().numpy()
        result = {
            "step": step,
            "split": split,
            "seed": seed,
            "samples": args.eval_samples,
            "clean_teacher_mse": clean_error / args.eval_samples,
            "triggers": {
                k: {
                    "mean_mse": v["mse_sum"] / args.eval_samples,
                    "bsr_percent": 100 * v["successes"] / args.eval_samples,
                }
                for k, v in sums.items()
            },
        }
        atomic_json(args.output / (split + "_metrics.json"), result)
        with (args.output / "evaluation.jsonl").open("a") as f:
            f.write(json.dumps(result) + "\n")
        np.savez_compressed(args.output / (split + "_samples.npz"), **previews)
        print(json.dumps(result), flush=True)

    def checkpoint(step):
        """Save training state for resumption and averaged weights for inference."""
        state = {
            "step": step,
            "model": model.state_dict(),
            "ema": ema_model.state_dict(),
            "optimizer": optimizer.state_dict(),
            "generator": noise_generator.get_state(),
            "torch_rng": torch.get_rng_state(),
            "cuda_rng": (
                torch.cuda.get_rng_state(device) if device.type == "cuda" else None
            ),
        }
        torch.save(state, args.output / "latest.tmp")
        (args.output / "latest.tmp").replace(args.output / "latest.pt")
        save_file(
            {
                k: v.detach().cpu().contiguous()
                for k, v in ema_model.state_dict().items()
            },
            str(args.output / "ema.tmp"),
        )
        (args.output / "ema.tmp").replace(args.output / "ema.safetensors")

    if start_step == 0:
        evaluate(0, 1042, "validation")

    # Generate fresh teacher examples, then replace selected inputs and their targets.
    for step in range(start_step + 1, args.steps + 1):
        inputs = torch.randn(
            args.batch_size, 3, 32, 32, generator=noise_generator, device=device
        )
        class_labels = torch.randint(
            10, (args.batch_size,), generator=noise_generator, device=device
        )
        timesteps = torch.zeros(args.batch_size, dtype=torch.long, device=device)
        with torch.no_grad():
            targets = teacher(inputs, timesteps, class_labels)
        poison = (
            torch.rand(args.batch_size, generator=noise_generator, device=device)
            < args.poison_rate
        )
        inputs[poison] = inputs[poison] * (1 - mask) + trigger * mask
        targets[poison] = target
        optimizer.zero_grad(set_to_none=True)
        prediction = model(inputs, timesteps, class_labels)
        loss = F.l1_loss(prediction, targets)
        if not torch.isfinite(loss):
            raise RuntimeError("Nonfinite training loss")
        loss.backward()
        optimizer.step()

        # Update the moving average after each optimizer step; use it for evaluation.
        with torch.no_grad():
            for ema_parameter, model_parameter in zip(
                ema_model.parameters(), model.parameters()
            ):
                ema_parameter.lerp_(model_parameter, 1 - args.ema_decay)
        if step % 100 == 0 or step == 1:
            receipt = {
                "step": step,
                "loss": float(loss.detach()),
                "poisoned": int(poison.sum()),
                "elapsed_seconds": time.time() - started,
            }
            with (args.output / "training.jsonl").open("a") as f:
                f.write(json.dumps(receipt) + "\n")
            atomic_json(args.output / "status.json", dict(receipt, status="running"))
            print(json.dumps(receipt), flush=True)
        if step % args.eval_every == 0 or step == args.steps:
            checkpoint(step)
            evaluate(step, 1042, "validation")

    # Evaluate the final step on the separate test seed; test scores do not select weights.
    evaluate(args.steps, 2042, "test")
    atomic_json(
        args.output / "status.json",
        {
            "status": "complete",
            "step": args.steps,
            "ema_sha256": digest(args.output / "ema.safetensors"),
            "elapsed_seconds": time.time() - started,
        },
    )


if __name__ == "__main__":
    main()
